version: '3'

services:
  app:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      default:
        ipv4_address: 172.20.0.8

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    networks:
      default:
        ipv4_address: 172.20.0.9



networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
